set(PICO_PLAYGROUND_URL_BASE "https://github.com/raspberrypi/pico-playground/tree/HEAD")
macro(playground_auto_set_url TARGET)
    file(RELATIVE_PATH URL_REL_PATH "${PICO_PLAYGROUND_PATH}" "${CMAKE_CURRENT_LIST_DIR}")
    pico_set_program_url(${TARGET} "${PICO_PLAYGROUND_URL_BASE}/${URL_REL_PATH}")
endmacro()
